title: Johan-Louis Coetzee
logo: /assests/img/Profile_Photo.jpg
description: |
  Contact Information:<br>
  Email: <a href="mailto:johanlouiscoetzee2003@gmail.com">Here</a><br>
  LinkedIn: <a href="https://www.linkedin.com/in/johan-louis-coetzee-29a89a320" target="_blank">Here</a><br>
#show_downloads: true
theme: jekyll-theme-minimal
